# services/ppt_service.py

import json
import tempfile

from pptx import Presentation
from pptx.util import Inches, Pt

from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE


# ============================================
# CHART PARSER
# ============================================

def extract_chart_data(chart_spec):

    if not chart_spec:
        return None

    # ============================================
    # STRING -> JSON
    # ============================================

    if isinstance(chart_spec, str):

        try:
            chart_spec = json.loads(chart_spec)

        except Exception:
            return None

    # ============================================
    # SIMPLE FORMAT
    # ============================================

    if (
        "labels" in chart_spec
        and "values" in chart_spec
    ):

        return {
            "type": chart_spec.get(
                "type",
                "bar"
            ),

            "title": chart_spec.get(
                "title",
                "Chart"
            ),

            "labels": chart_spec["labels"],

            "values": chart_spec["values"],
        }

    # ============================================
    # VEGA-LITE FORMAT
    # ============================================

    try:

        mark = chart_spec.get(
            "mark",
            "bar"
        )

        # mark can sometimes be object
        if isinstance(mark, dict):

            mark = mark.get(
                "type",
                "bar"
            )

        data_values = (
            chart_spec
            .get("data", {})
            .get("values", [])
        )

        encoding = chart_spec.get(
            "encoding",
            {}
        )

        labels = []
        values = []

        dimension_field = None
        measure_field = None

        # ============================================
        # FIND DIMENSION + MEASURE
        # ============================================

        for channel in encoding.values():

            if not isinstance(channel, dict):
                continue

            field = channel.get("field")

            field_type = channel.get("type")

            if not field:
                continue

            # categorical
            if (
                field_type == "nominal"
                and dimension_field is None
            ):

                dimension_field = field

            # numeric
            elif (
                field_type == "quantitative"
                and measure_field is None
            ):

                measure_field = field

        # ============================================
        # FALLBACK
        # ============================================

        if not dimension_field or not measure_field:

            return None

        # ============================================
        # EXTRACT VALUES
        # ============================================

        for row in data_values:

            labels.append(
                str(
                    row.get(
                        dimension_field
                    )
                )
            )

            values.append(
                float(
                    row.get(
                        measure_field,
                        0
                    )
                )
            )

        return {

            "type": mark,

            "title": chart_spec.get(
                "title",
                "Chart"
            ),

            "labels": labels,

            "values": values,
        }

    except Exception as e:

        print(
            "Chart parsing error:",
            str(e)
        )

        return None

def get_chart_type(chart_type):

    if chart_type == "line":

        return XL_CHART_TYPE.LINE

    elif chart_type == "pie":

        return XL_CHART_TYPE.PIE

    return XL_CHART_TYPE.COLUMN_CLUSTERED


# ============================================
# PPT GENERATOR
# ============================================

def generate_pptx(
    presentation_json: dict,
    include_charts: bool = True
):

    prs = Presentation()

    # ============================================
    # TITLE SLIDE
    # ============================================

    title_slide_layout = prs.slide_layouts[0]

    title_slide = prs.slides.add_slide(
        title_slide_layout
    )

    title_slide.shapes.title.text = (
        presentation_json.get(
            "presentation_title",
            "Analysis Summary"
        )
    )

    title_slide.placeholders[1].text = (
        "Generated by Cortex PPT Export"
    )

    # ============================================
    # MAIN INSIGHT SLIDE
    # ============================================

    slide_data = presentation_json.get(
        "slide",
        {}
    )

    slide_layout = prs.slide_layouts[6]

    slide = prs.slides.add_slide(
        slide_layout
    )

    # ============================================
    # SLIDE TITLE
    # ============================================

    title_box = slide.shapes.add_textbox(
        Inches(0.5),
        Inches(0.3),
        Inches(9),
        Inches(0.6)
    )

    title_tf = title_box.text_frame

    title_tf.text = slide_data.get(
        "title",
        "Key Insights"
    )

    title_tf.paragraphs[0].font.size = Pt(24)

    # ============================================
    # BULLETS LEFT SIDE
    # ============================================

    body_box = slide.shapes.add_textbox(
        Inches(0.5),
        Inches(1.2),

        # reduced width to prevent overlap
        Inches(3.6),

        Inches(4.5)
    )

    tf = body_box.text_frame

    tf.clear()

    # IMPORTANT
    # prevents overflow without expensive autosizing
    text_frame = body_box.text_frame
    text_frame.word_wrap = True

    # ============================================
    # BULLETS
    # ============================================

    bullets = slide_data.get(
        "bullets",
        []
    )

    for idx, bullet in enumerate(bullets):

        if idx == 0:

            p = tf.paragraphs[0]

        else:

            p = tf.add_paragraph()

        # Manual bullet symbol
        p.text = f"• {bullet}"

        p.level = 0

        p.font.size = Pt(16)

        p.space_after = Pt(10)

    # ============================================
    # CHART RIGHT SIDE
    # ============================================

    if include_charts:

        parsed_chart = extract_chart_data(
            presentation_json.get(
                "chart_spec"
            )
        )

        if parsed_chart:

            chart_data = CategoryChartData()

            chart_data.categories = (
                parsed_chart["labels"]
            )

            chart_data.add_series(
                "Series 1",
                parsed_chart["values"]
            )

            chart = slide.shapes.add_chart(
                get_chart_type(
                    parsed_chart["type"]
                ),

                # moved chart further right
                Inches(4.4),

                Inches(1.3),

                # slightly smaller chart
                Inches(4.8),

                Inches(3.8),

                chart_data
            ).chart

            chart.has_legend = False

            chart.has_title = True

            chart.chart_title.text_frame.text = (
                parsed_chart.get(
                    "title",
                    "Chart"
                )
            )

    # ============================================
    # SAVE
    # ============================================

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pptx"
    )

    prs.save(temp_file.name)

    return temp_file.name